@startuml
'https://plantuml.com/sequence-diagram

class Solution43{
    +createWebsite()

}
class IO{
    -takeInputs()
    +getSiteIn()
    +getAuthIn()
    +getJss()
    +getCss()

}

Solution43 --> IO
@enduml